# Generated by Django 4.2.7 on 2023-11-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pubdate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
