# Generated by Django 4.2.7 on 2023-11-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_alter_post_options_remove_advuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='department',
            field=models.CharField(choices=[('adm', 'Администратор'), ('emp', 'Группа акустики и ЭМП')], max_length=50, null=True, verbose_name='Группа'),
        ),
    ]
