# Generated by Django 4.2.7 on 2023-11-02 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_advuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер заявки')),
                ('name', models.TextField(null=True, verbose_name='Название заявки')),
                ('comment', models.TextField(null=True, verbose_name='Примечание')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
