# Generated by Django 4.2.7 on 2023-11-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_application_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='num',
            field=models.CharField(max_length=50, verbose_name='Номер заявки'),
        ),
    ]
