# Generated by Django 4.2.7 on 2023-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_alter_application_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, verbose_name='Номер услуги')),
                ('name', models.TextField(null=True, verbose_name='Название услуги')),
                ('comment', models.TextField(null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайс',
            },
        ),
    ]
