# Generated by Django 4.2.6 on 2023-11-05 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='department',
            field=models.CharField(choices=[('adm', 'Администратор'), ('emp', 'Группа акустики и ЭМП')], max_length=50, null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
