# Generated by Django 4.2.6 on 2023-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_pricelist_department_pricelist_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pricelist',
            field=models.ManyToManyField(blank=True, to='helper.pricelist', verbose_name='Пункты прайслиста'),
        ),
    ]
