# Generated by Django 4.2.6 on 2024-01-29 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_application_pricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListFiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, verbose_name='Номер услуги')),
                ('name', models.TextField(null=True, verbose_name='Название услуги')),
                ('time', models.CharField(max_length=50, verbose_name='Срок выполнения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('department', models.CharField(choices=[('adm', 'Администратор'), ('emp', 'Группа акустики и ЭМП')], max_length=50, null=True, verbose_name='Группа')),
                ('price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайс',
            },
        ),
        migrations.CreateModel(
            name='PriceListUr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, verbose_name='Номер услуги')),
                ('name', models.TextField(null=True, verbose_name='Название услуги')),
                ('ed', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('department', models.CharField(choices=[('adm', 'Администратор'), ('emp', 'Группа акустики и ЭМП')], max_length=50, null=True, verbose_name='Группа')),
                ('price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тариф без НДС')),
                ('priceNDS', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тариф с НДС')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайс',
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='pricelist',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
        migrations.AddField(
            model_name='application',
            name='pricelistFiz',
            field=models.ManyToManyField(blank=True, to='helper.pricelistfiz', verbose_name='Пункты прайслиста физические лица'),
        ),
        migrations.AddField(
            model_name='application',
            name='pricelistUr',
            field=models.ManyToManyField(blank=True, to='helper.pricelistur', verbose_name='Пункты прайслиста юридические лица'),
        ),
    ]
