# Generated by Django 4.2.6 on 2024-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_pricelistfiz_pricelistur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Название группы/отдела')),
            ],
            options={
                'verbose_name': 'Группа/отдел',
                'verbose_name_plural': 'Группы/отделы',
            },
        ),
        migrations.AlterModelOptions(
            name='pricelistfiz',
            options={'verbose_name': 'Прайс физические лица', 'verbose_name_plural': 'Прайс физические лица'},
        ),
        migrations.AlterModelOptions(
            name='pricelistur',
            options={'verbose_name': 'Прайс юридические лица', 'verbose_name_plural': 'Прайс юридические лица'},
        ),
        migrations.AddField(
            model_name='pricelistur',
            name='section',
            field=models.CharField(choices=[('1', '1.Санитарно-гигиенические услуги'), ('1a', '1A.Санитарно-гигиенические услуги-административные процедуры'), ('2', '2.Отбор проб, органолептические и физико-химические (санитарно-химические) исследования объектов окружающей среды'), ('3', '3.Физико-химические и инструментальные исследования и испытания продукции'), ('4', '4.Измерения (исследования) физических факторов окружающей и производственной среды'), ('5', '5.Радиологические исследования и измерения'), ('6', '6.Микробиологические исследования'), ('7', '7.Токсикологические, биохимические и гематологические исследования'), ('8', '8.'), ('san', 'Санитарно-эпидемиологические услуги для нерезидентов'), ('9', '9.Административные процедуры, осуществляемые в отношении субъектов хозяйствования'), ('test', 'Тестирование на инфекцию COVID-19 методом ПЦР в режиме реального времени')], max_length=50, null=True, verbose_name='Раздел'),
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='pricelistfiz',
            name='department',
        ),
        migrations.RemoveField(
            model_name='pricelistur',
            name='department',
        ),
        migrations.AddField(
            model_name='advuser',
            name='department',
            field=models.ManyToManyField(blank=True, to='helper.department', verbose_name='Группа/отдел'),
        ),
        migrations.AddField(
            model_name='pricelistfiz',
            name='department',
            field=models.ManyToManyField(blank=True, to='helper.department', verbose_name='Группа/отдел'),
        ),
        migrations.AddField(
            model_name='pricelistur',
            name='department',
            field=models.ManyToManyField(blank=True, to='helper.department', verbose_name='Группа/отдел'),
        ),
    ]
