# Generated by Django 4.2.6 on 2024-03-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_department_alter_pricelistfiz_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='department',
        ),
        migrations.AddField(
            model_name='advuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.department', verbose_name='Группа/отдел'),
        ),
    ]
