# Generated by Django 4.2.6 on 2024-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0013_applicationf_applicationu_delete_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationf',
            options={'verbose_name': 'Заявка ф.л', 'verbose_name_plural': 'Заявки ф.л'},
        ),
        migrations.AlterModelOptions(
            name='applicationu',
            options={'verbose_name': 'Заявка ю.л', 'verbose_name_plural': 'Заявки ю.л'},
        ),
        migrations.RemoveField(
            model_name='applicationu',
            name='pricelistFiz',
        ),
        migrations.AddField(
            model_name='applicationu',
            name='pricelistUr',
            field=models.ManyToManyField(blank=True, to='helper.pricelistur', verbose_name='Пункты прайслиста физические лица'),
        ),
    ]
