# Generated by Django 4.2.6 on 2024-03-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0014_alter_applicationf_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationf',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активная заявка'),
        ),
        migrations.AddField(
            model_name='applicationu',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активная заявка'),
        ),
    ]
