# Generated by Django 4.2.6 on 2024-03-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0016_remove_pricelistur_price_remove_pricelistur_pricends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='department',
        ),
        migrations.AddField(
            model_name='advuser',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='helper.department', verbose_name='Группа/отдел'),
        ),
    ]
